// // import '../styles/globals.css';

// import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';

// import Header from '@/components/home/header';
// import HeaderMobile from '@/components/home/header-mobile';
// import MarginWidthWrapper from '@/components/home/margin-width-wrapper';
// import PageWrapper from '@/components/home/page-wrapper';
// import SideNav from '@/components/home/side-nav';
// import Signout from '@/components/home/Signout';

// const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//   title: 'Side Nav w/ submenus',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={`bg-white${inter.className}`}>
//         <div className="flex">
//           <SideNav />
//           <main className="flex-1">
//             <MarginWidthWrapper>
//               <Signout/>
//               <Header />
//               <HeaderMobile />
//               <PageWrapper>{children}</PageWrapper>
//             </MarginWidthWrapper>
//           </main>
//         </div>
//       </body>
//     </html>
//   );
// }

import "@/styles/globals.css";
import type { Metadata } from 'next';
import { Providers } from "./providers";
import { fontSans } from '../../../config/fonts';
import clsx from "clsx";
import Modal from "@/components/auth/modal";
import Signout from "@/components/home/Signout";

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={clsx("font-sans antialiased", fontSans.className)}>
      <Signout/>
        
        <Providers>
          {/* <Modal /> */}
          {children}
        </Providers>
      </body>
    </html>
  )
}


